name: Export Anthony report to DOCX

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Convert Markdown to DOCX (Anthony)
        shell: bash
        run: |
          set -euo pipefail
          pandoc "docs/TESIS_ProyectoFinal_Anthony_Grijalva.md" \
            -o "TESIS_ProyectoFinal_Anthony_Grijalva.docx" \
            --from gfm+raw_html+raw_attribute \
            --toc --toc-depth=3 \
            --metadata=title:"Evaluación Integral de Calidad de Software" \
            --metadata=author:"Anthony Grijalva" \
            --metadata=subtitle:"Universidad Mariano Gálvez de Guatemala · Ingeniería en Sistemas de Información · Sede Chiquimulilla"

      - name: Upload DOCX artifact
        uses: actions/upload-artifact@v4
        with:
          name: TESIS_ProyectoFinal_Anthony_Grijalva.docx
          path: TESIS_ProyectoFinal_Anthony_Grijalva.docx
          if-no-files-found: error
