name: Export thesis to DOCX (artifact only)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Convert Markdown to DOCX
        run: |
          pandoc docs/TESIS_ProyectoFinal_Marco_Tulio.md \
            -o TESIS_ProyectoFinal_Marco_Tulio.docx \
            --from gfm \
            --toc \
            --metadata=title:"Proyecto Final – Aseguramiento de la Calidad"

      - name: Upload DOCX artifact
        uses: actions/upload-artifact@v4
        with:
          name: TESIS_ProyectoFinal_Marco_Tulio.docx
          path: TESIS_ProyectoFinal_Marco_Tulio.docx
          if-no-files-found: error
